---
title: "About www.bpsmscp.org.uk"
author: "Mark Andrews"
date: 2019-01-12
tags: ["website-info"]
description: How the www.bpsmscp.org.uk is built, how it will be maintained and developed, what will contain, and how it will be used.
---


The *www.bpsmscp.org.uk* website is built with
[blogdown](https://github.com/rstudio/blogdown) and [Hugo](https://gohugo.io/).
[Hugo](https://gohugo.io/) is a *"a fast and modern static site generator
written in [Go](https://golang.org/)"*.
[Blogdown](https://github.com/rstudio/blogdown) allows webpages to be written
in [RMarkdown](https://rmarkdown.rstudio.com/), including using R code as per
normal with [RMarkdown](https://rmarkdown.rstudio.com/), and these pages are
then integrated into static site generated by [Hugo](https://gohugo.io/).  It
is currently hosted, and no cost (thank you) by
[netlify](https://www.netlify.com/).


## Website content

The site primarily consists of two parts: the [blog](blog) and the
[wiki](wiki).  The [blog](blog) is a regular blog where we'll post news or
announcements related to the section, as well as more or less anything else
that we think is relevant or interesting and related to the topic of maths,
stats, or computing in psychology.  The [wiki](wiki), on the other hand, is
intended to develop into a collection of notes, guides, and *how-tos* on
various maths, stats, and computing topics

## Version control, maintenance and development 

All the source content, including this page, is written in *.Rmd* files, which
are under [Git](https://git-scm.com/) version control. The Git repository
publicly hosted on [GitHub](https://github.com/). Included in the repository
are all the [Hugo](https://gohugo.io/) templates and css style files. The
current theme of the site is based on my hacking of the [Hugo
Bingo](https://themes.gohugo.io/hugo-bingo/) theme by [Bing-Sheng
Chen](https://bschen.tw) (thank you).
We'll use the [GitHub repository's "Issues" pages](https://github.com/) to
discuss problems with the site and changes and improvements that we can make.

## Contributing to this website

Anyone who would like to add a blog post or a wiki page, will do so via a
[pull request from a
fork](https://help.github.com/articles/creating-a-pull-request-from-a-fork/).
At the moment, I appreciate that that might seem like a bizarre 
concept to many people, and thus quite off-putting, but I hope that in time its
intrinsic elegance will be seen and it will be appreciated that there just is no
better way than this. More details on how to do this will be provided (eventually)
on the [GitHub repository wiki page](https://github.com/).

## A minimal viable product

At the moment, the website has just enough to get started but no more. There
are already changes and improvements that I can envisage, but these can be
added in time. 

Long live the *www.bpsmscp.org.uk* website.
